### ISSUE TITLE
Public to-do List

### ISSUE THREAD

**Issue by OfficialCRUGG** [OfficialCRUGG/MaiSakurajima#1]
Here's a public to-do list. If you'd like to work on any of these features, reply or message me privately that you'd like to do so. I'll then assign you to it! If you would like anything to be added to the list, create a feature request issue.
- [ ] Improve Word Cloud on Mobile (Nobody assigned)
- [ ] Smooth-ify Scroll (Nobody assigned)
- [ ] Allow scrolling only in steps of screen height on Gallery Page (Nobody assigned)
- [ ] Quotes page to randomly show a **spoiler-free** quote from the anime/movie including episode it's from (Nobody assigned)
- [ ] Add lazy loading to images (Nobody assigned)
